# Generated by Django 2.1.5 on 2019-03-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurdoWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('category', models.IntegerField(choices=[(0, 'time'), (1, 'nation')])),
                ('video_link', models.CharField(max_length=255)),
            ],
        ),
    ]
