# Generated by Django 2.1.5 on 2019-04-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0003_auto_20190401_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surdoword',
            name='category',
            field=models.IntegerField(choices=[(0, 'Время, календарь'), (1, 'Алфавит'), (2, 'Знакомство'), (3, 'Человек'), (4, 'Семья'), (5, 'Названия месяцев'), (6, 'Дни недели'), (7, 'Природа'), (8, 'Времена года')], default=0, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='surdoword',
            name='name_kz',
            field=models.CharField(max_length=255, verbose_name='Название (каз)'),
        ),
        migrations.AlterField(
            model_name='surdoword',
            name='name_ru',
            field=models.CharField(max_length=255, verbose_name='Название (рус)'),
        ),
        migrations.AlterField(
            model_name='surdoword',
            name='video_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на ютуб'),
        ),
    ]
