# Generated by Django 2.1.5 on 2019-04-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0004_auto_20190401_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surdoword',
            name='video_link',
        ),
        migrations.AddField(
            model_name='surdoword',
            name='video_link_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на ютуб (каз)'),
        ),
        migrations.AddField(
            model_name='surdoword',
            name='video_link_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на ютуб (рус)'),
        ),
    ]
